// <auto-generated />
using System;
using AttenDancer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttenDancer.Data.Migrations
{
    [DbContext(typeof(AttenDancerDbContext))]
    partial class AttenDancerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttenDancer.Entity.Entity_Models.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EventGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = "abcf9f45-d59d-4229-b13a-28e9a35718ca",
                            EventGroupId = "18f2745f-652e-4817-b7e1-ea7787fc71c8",
                            Name = "Adatbázisok - 1. előadás",
                            QrCode = "QR_CODE_EVENT_1_ABC123",
                            UserId = "22f10921-4a13-48ce-aaf8-61f99c0e3433"
                        },
                        new
                        {
                            Id = "58148cbb-f925-45ee-a4a1-17e2f981c8bc",
                            EventGroupId = "18f2745f-652e-4817-b7e1-ea7787fc71c8",
                            Name = "Adatbázisok - 2. előadás",
                            QrCode = "QR_CODE_EVENT_2_DEF456",
                            UserId = "22f10921-4a13-48ce-aaf8-61f99c0e3433"
                        });
                });

            modelBuilder.Entity("AttenDancer.Entity.Entity_Models.EventGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EventGroups");

                    b.HasData(
                        new
                        {
                            Id = "18f2745f-652e-4817-b7e1-ea7787fc71c8",
                            Name = "Adatbázisok 2024/25 őszi félév",
                            UserId = "22f10921-4a13-48ce-aaf8-61f99c0e3433"
                        });
                });

            modelBuilder.Entity("AttenDancer.Entity.Entity_Models.Participant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId", "EventId")
                        .IsUnique();

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            Id = "c2f8c2ea-d385-466f-ad97-74c762114fc1",
                            Date = new DateTime(2025, 9, 30, 16, 2, 20, 252, DateTimeKind.Utc).AddTicks(9410),
                            EventId = "abcf9f45-d59d-4229-b13a-28e9a35718ca",
                            Metadata = "{\"neptun\":\"ABC123\",\"seat\":\"12A\"}",
                            UserId = "b5f30803-2ff2-42a3-8353-20fc04bd0992"
                        },
                        new
                        {
                            Id = "cc3e1c61-b5ca-4042-a7b8-d2505d433530",
                            Date = new DateTime(2025, 9, 30, 16, 2, 20, 252, DateTimeKind.Utc).AddTicks(9856),
                            EventId = "abcf9f45-d59d-4229-b13a-28e9a35718ca",
                            Metadata = "{\"neptun\":\"DEF456\",\"seat\":\"15B\"}",
                            UserId = "843f06a0-befe-48a3-8a3d-6ad8ca807670"
                        },
                        new
                        {
                            Id = "e2580ebc-b428-47b0-852b-0453d580414e",
                            Date = new DateTime(2025, 10, 1, 16, 2, 20, 252, DateTimeKind.Utc).AddTicks(9862),
                            EventId = "58148cbb-f925-45ee-a4a1-17e2f981c8bc",
                            Metadata = "{\"neptun\":\"ABC123\",\"seat\":\"10C\"}",
                            UserId = "b5f30803-2ff2-42a3-8353-20fc04bd0992"
                        });
                });

            modelBuilder.Entity("AttenDancer.Entity.Entity_Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "22f10921-4a13-48ce-aaf8-61f99c0e3433",
                            Email = "janos.kovacs@example.com",
                            FirstName = "János",
                            LastName = "Kovács",
                            Password = "hashed_password_123"
                        },
                        new
                        {
                            Id = "b5f30803-2ff2-42a3-8353-20fc04bd0992",
                            Email = "anna.nagy@example.com",
                            FirstName = "Anna",
                            LastName = "Nagy",
                            Password = "hashed_password_456"
                        },
                        new
                        {
                            Id = "843f06a0-befe-48a3-8a3d-6ad8ca807670",
                            Email = "peter.toth@example.com",
                            FirstName = "Péter",
                            LastName = "Tóth",
                            Password = "hashed_password_789"
                        });
                });

            modelBuilder.Entity("AttenDancer.Entity.Entity_Models.Event", b =>
                {
                    b.HasOne("AttenDancer.Entity.Entity_Models.EventGroup", "EventGroup")
                        .WithMany("Events")
                        .HasForeignKey("EventGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AttenDancer.Entity.Entity_Models.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttenDancer.Entity.Entity_Models.EventGroup", b =>
                {
                    b.HasOne("AttenDancer.Entity.Entity_Models.User", "User")
                        .WithMany("EventGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttenDancer.Entity.Entity_Models.Participant", b =>
                {
                    b.HasOne("AttenDancer.Entity.Entity_Models.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttenDancer.Entity.Entity_Models.User", "User")
                        .WithMany("Participants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttenDancer.Entity.Entity_Models.Event", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("AttenDancer.Entity.Entity_Models.EventGroup", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("AttenDancer.Entity.Entity_Models.User", b =>
                {
                    b.Navigation("EventGroups");

                    b.Navigation("Events");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
