// <auto-generated />
using AttenDancer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttenDancer.Migrations
{
    [DbContext(typeof(AttenDancerDbContext))]
    [Migration("20250920102127_CreateDbWithExampleData")]
    partial class CreateDbWithExampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttenDancer.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 47,
                            FullName = "Kai Le",
                            JobTitle = "Controls Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Age = 38,
                            FullName = "Robert Patel",
                            JobTitle = "Analyst"
                        },
                        new
                        {
                            Id = 3,
                            Age = 52,
                            FullName = "Cameron Lo",
                            JobTitle = "Network Administrator"
                        },
                        new
                        {
                            Id = 4,
                            Age = 44,
                            FullName = "Harper Castillo",
                            JobTitle = "Director"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
