export const environment = {
  production: false,
  apis: {
    base: "https://localhost:7198",
    login: "https://localhost:7198/api/User/login",
    register: "https://localhost:7198/api/User/register",
    getUser: 'https://localhost:7198/api/User',
    getUserMe: 'https://localhost:7198/api/User/me',
    updateUser: 'https://localhost:7198/api/User',
    changePassword: 'https://localhost:7198/api/User/{id}/password',
    deleteAccount: 'https://localhost:7198/api/User',
    postEvent: 'https://localhost:7198/api/Event',
    postEventGroup: 'https://localhost:7198/api/EventGroup',
    updateEvent: 'https://localhost:7198/api/Event/{id}',
    updateEventGroup: 'https://localhost:7198/api/EventGroup/{id}',
    eventGroupView: 'https://localhost:7198/api/EventGroup/{eventGroupId}/matrix',
    eventGroupByUserId: 'https://localhost:7198/api/EventGroup/ByUserId',
    eventsByUser: 'https://localhost:7198/GetEventsByUserId',
    deleteEvent: 'https://localhost:7198/api/Event/{id}',
  },
  tokenKey: 'attendancer-jwt-token',
};
